export enum NotificationType {
  BUDGET_READY = 'BUDGET_READY',
  PAYMENT_LINK_READY = 'PAYMENT_LINK_READY',
  STOCK_PARTS_REQUESTED = 'STOCK_PARTS_REQUESTED',
  SERVICE_ORDER_STATUS_CHANGED = 'SERVICE_ORDER_STATUS_CHANGED',
}
