/** Estados do orçamento (§7.2): GERADO -> AGUARDANDO_APROVAÇÃO -> ACEITO/RECUSADO. */
export enum BudgetStatus {
  GENERATED = 'GENERATED',
  WAITING_APPROVAL = 'WAITING_APPROVAL',
  ACCEPTED = 'ACCEPTED',
  REFUSED = 'REFUSED',
}
