import { SmokeCollection, SmokeStep } from './types';

const auth = { bearerTokenVar: 'accessToken' };
const json = { 'Content-Type': 'application/json' };

const stopOnError = [
  'if (res.getStatus() >= 400) {',
  '  bru.runner.setNextRequest(null);',
  '}',
];

const captureId = (name: string): string[] => [
  'if (res.getStatus() === 200 || res.getStatus() === 201) {',
  `  bru.setVar("${name}", res.getBody().id);`,
  '} else {',
  '  bru.runner.setNextRequest(null);',
  '}',
];

const steps: SmokeStep[] = [
  {
    sequence: 0,
    slug: 'gerar-dados',
    name: 'Gerar dados do smoke',
    method: 'GET',
    url: '{{baseUrl}}/health',
    preRequest: [
      'const useRandomData = String(bru.getEnvVar("useRandomData")).toLowerCase() !== "false";',
      'if (!useRandomData) {',
      '  const runId = Date.now();',
      '  bru.setVar("runId", runId);',
      '  bru.setVar("stockIdempotencyKey", `${bru.getEnvVar("stockIdempotencyKey")}-${runId}`);',
      '  return;',
      '}',
      'const rnd = (n) => Math.floor(Math.random() * n);',
      'const pick = (items) => items[rnd(items.length)];',
      'const letter = () => String.fromCharCode(65 + rnd(26));',
      'const runId = Date.now();',
      'const cnpjBase = Array.from({ length: 8 }, () => rnd(10)).concat([0, 0, 0, 1]);',
      'const cnpjDigit = (digits, weights) => {',
      '  const sum = digits.reduce((acc, digit, index) => acc + digit * weights[index], 0);',
      '  const rest = sum % 11;',
      '  return rest < 2 ? 0 : 11 - rest;',
      '};',
      'const cnpjD1 = cnpjDigit(cnpjBase, [5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]);',
      'const cnpjD2 = cnpjDigit([...cnpjBase, cnpjD1], [6, 5, 4, 3, 2, 9, 8, 7, 6, 5, 4, 3, 2]);',
      'const suffix = (runId % 0xffffffffffff).toString(16).padStart(12, "0");',
      'const firstNames = ["Ana", "Bruno", "Carla", "Diego", "Elisa", "Felipe"];',
      'const lastNames = ["Silva", "Souza", "Pereira", "Oliveira", "Costa", "Lima"];',
      'const brands = ["Fiat", "Volkswagen", "Chevrolet", "Toyota", "Honda", "Renault"];',
      'const modelsByBrand = {',
      '  Fiat: ["Argo", "Pulse", "Cronos"],',
      '  Volkswagen: ["Polo", "Virtus", "T-Cross"],',
      '  Chevrolet: ["Onix", "Tracker", "Spin"],',
      '  Toyota: ["Corolla", "Yaris", "Hilux"],',
      '  Honda: ["City", "HR-V", "Civic"],',
      '  Renault: ["Kwid", "Duster", "Sandero"],',
      '};',
      'const services = [',
      '  ["Troca de oleo e filtro", "Substituicao de oleo, filtro e revisao visual"],',
      '  ["Revisao de freios", "Inspecao e ajuste do sistema de freio"],',
      '  ["Alinhamento e balanceamento", "Ajuste de geometria e balanceamento das rodas"],',
      '];',
      'const parts = [',
      '  ["OIL-FILTER", "Filtro de oleo", "Filtro para oleo do motor"],',
      '  ["BRAKE-PAD", "Pastilha de freio", "Jogo de pastilhas dianteiras"],',
      '  ["AIR-FILTER", "Filtro de ar", "Filtro do sistema de admissao"],',
      '];',
      'const clientName = `${pick(firstNames)} ${pick(lastNames)}`;',
      'const brand = pick(brands);',
      'const model = pick(modelsByBrand[brand]);',
      'const service = pick(services);',
      'const part = pick(parts);',
      'bru.setVar("runId", runId);',
      'bru.setVar("clientName", clientName);',
      'bru.setVar("document", [...cnpjBase, cnpjD1, cnpjD2].join(""));',
      'bru.setVar("plate", `${letter()}${letter()}${letter()}${rnd(10)}${letter()}${rnd(10)}${rnd(10)}`);',
      'bru.setVar("clientEmail", `${clientName.toLowerCase().replace(" ", ".")}.${runId}@example.com`);',
      'bru.setVar("clientPhone", `(11) 9${String(rnd(100000000)).padStart(8, "0")}`);',
      'bru.setVar("vehicleBrand", brand);',
      'bru.setVar("vehicleModel", model);',
      'bru.setVar("vehicleYear", 2018 + rnd(8));',
      'bru.setVar("serviceName", `${service[0]} ${runId}`);',
      'bru.setVar("serviceDescription", service[1]);',
      'bru.setVar("partCode", `${part[0]}-${runId}`);',
      'bru.setVar("partName", part[1]);',
      'bru.setVar("partDescription", part[2]);',
      'bru.setVar("serviceOrderDescription", `${pick(["Barulho", "Vibracao", "Falha intermitente"])} em ${model}`);',
      'bru.setVar("budgetServiceDescription", service[0]);',
      'bru.setVar("budgetPartDescription", part[1]);',
      'bru.setVar("stockIdempotencyKey", `entrada-${runId}`);',
      'bru.setVar("mechanicId", `00000000-0000-4000-8000-${suffix}`);',
    ],
    tests: [
      'test("dados do smoke preparados", function () {',
      '  expect(res.getStatus()).to.equal(200);',
      '  expect(bru.getVar("runId")).to.exist;',
      '  expect(bru.getVar("clientEmail")).to.contain("@");',
      '});',
      ...stopOnError,
    ],
  },
  {
    sequence: 1,
    slug: 'health-check',
    name: 'Health check',
    method: 'GET',
    url: '{{baseUrl}}/health',
    tests: [
      'test("API responde health check", function () {',
      '  expect(res.getStatus()).to.equal(200);',
      '});',
      ...stopOnError,
    ],
  },
  {
    sequence: 2,
    slug: 'login',
    name: 'Login',
    method: 'POST',
    url: '{{baseUrl}}/auth/login',
    headers: json,
    body: { email: '{{email}}', password: '{{password}}' },
    tests: [
      'test("login retorna tokens", function () {',
      '  expect(res.getStatus()).to.equal(200);',
      '  expect(res.getBody().accessToken).to.be.a("string").and.not.empty;',
      '  expect(res.getBody().refreshToken).to.be.a("string").and.not.empty;',
      '});',
      'if (res.getStatus() === 200) {',
      '  bru.setVar("accessToken", res.getBody().accessToken);',
      '  bru.setVar("refreshToken", res.getBody().refreshToken);',
      '} else {',
      '  bru.runner.setNextRequest(null);',
      '}',
    ],
  },
  {
    sequence: 3,
    slug: 'cria-cliente',
    name: 'Cria cliente',
    method: 'POST',
    url: '{{baseUrl}}/clients',
    auth,
    headers: json,
    body: {
      name: '{{clientName}}',
      document: '{{document}}',
      email: '{{clientEmail}}',
      phone: '{{clientPhone}}',
    },
    tests: [
      'test("cliente criado", function () { expect(res.getStatus()).to.equal(201); });',
      ...captureId('clientId'),
    ],
  },
  {
    sequence: 4,
    slug: 'cadastra-veiculo',
    name: 'Cadastra veiculo',
    method: 'POST',
    url: '{{baseUrl}}/vehicles',
    auth,
    headers: json,
    body: {
      clientId: '{{clientId}}',
      plate: '{{plate}}',
      brand: '{{vehicleBrand}}',
      model: '{{vehicleModel}}',
      year: '{{vehicleYear}}',
    },
    tests: [
      'test("veiculo criado", function () { expect(res.getStatus()).to.equal(201); });',
      ...captureId('vehicleId'),
    ],
  },
  {
    sequence: 5,
    slug: 'cadastra-servico-catalogo',
    name: 'Cadastra servico no catalogo',
    method: 'POST',
    url: '{{baseUrl}}/services',
    auth,
    headers: json,
    body: {
      name: '{{serviceName}}',
      description: '{{serviceDescription}}',
      price: 149.9,
    },
    tests: [
      'test("servico criado", function () { expect(res.getStatus()).to.equal(201); });',
      ...captureId('serviceId'),
    ],
  },
  {
    sequence: 6,
    slug: 'cadastra-peca',
    name: 'Cadastra peca',
    method: 'POST',
    url: '{{baseUrl}}/parts',
    auth,
    headers: json,
    body: {
      code: '{{partCode}}',
      name: '{{partName}}',
      description: '{{partDescription}}',
      type: 'PART',
      unit: 'UNIT',
      unitPrice: 49.9,
      minimumQuantity: 3,
    },
    tests: [
      'test("peca criada", function () { expect(res.getStatus()).to.equal(201); });',
      ...captureId('partId'),
    ],
  },
  {
    sequence: 7,
    slug: 'entrada-estoque',
    name: 'Entrada no estoque',
    method: 'POST',
    url: '{{baseUrl}}/parts/{{partId}}/movements/in',
    auth,
    headers: json,
    body: { quantity: 10, idempotencyKey: '{{stockIdempotencyKey}}' },
    tests: [
      'test("entrada registrada", function () { expect(res.getStatus()).to.equal(201); });',
      ...stopOnError,
    ],
  },
  {
    sequence: 8,
    slug: 'abre-ordem-servico',
    name: 'Abre ordem de servico',
    method: 'POST',
    url: '{{baseUrl}}/service-orders',
    auth,
    headers: json,
    body: {
      clientId: '{{clientId}}',
      vehicleId: '{{vehicleId}}',
      description: '{{serviceOrderDescription}}',
    },
    tests: [
      'test("OS aberta", function () { expect(res.getStatus()).to.equal(201); });',
      ...captureId('serviceOrderId'),
    ],
  },
  {
    sequence: 9,
    slug: 'atribui-mecanico',
    name: 'Atribui mecanico',
    method: 'PATCH',
    url: '{{baseUrl}}/service-orders/{{serviceOrderId}}/assign',
    auth,
    headers: json,
    body: { mechanicId: '{{mechanicId}}' },
    tests: [
      'test("mecanico atribuido", function () { expect(res.getStatus()).to.equal(200); });',
      ...stopOnError,
    ],
  },
  {
    sequence: 10,
    slug: 'gera-orcamento',
    name: 'Gera orcamento',
    method: 'POST',
    url: '{{baseUrl}}/budgets',
    auth,
    headers: json,
    body: {
      serviceOrderId: '{{serviceOrderId}}',
      items: [
        {
          serviceId: '{{serviceId}}',
          description: '{{budgetServiceDescription}}',
          type: 'SERVICE',
          quantity: 1,
          unitPrice: 149.9,
        },
        {
          partId: '{{partId}}',
          description: '{{budgetPartDescription}}',
          type: 'PART',
          quantity: 1,
          unitPrice: 49.9,
        },
      ],
    },
    tests: [
      'test("orcamento criado com total esperado", function () {',
      '  expect(res.getStatus()).to.equal(201);',
      '  expect(res.getBody().totalAmount).to.equal(199.8);',
      '});',
      ...captureId('budgetId'),
    ],
  },
  {
    sequence: 11,
    slug: 'envia-orcamento-cliente',
    name: 'Envia orcamento ao cliente',
    method: 'POST',
    url: '{{baseUrl}}/budgets/{{budgetId}}/send',
    auth,
    tests: [
      'test("orcamento enviado", function () { expect(res.getStatus()).to.equal(200); });',
      ...stopOnError,
    ],
  },
  {
    sequence: 12,
    slug: 'aceita-orcamento',
    name: 'Aceita orcamento',
    method: 'POST',
    url: '{{baseUrl}}/budgets/{{budgetId}}/accept',
    auth,
    tests: [
      'test("orcamento aceito", function () { expect(res.getStatus()).to.equal(200); });',
      ...stopOnError,
    ],
  },
  {
    sequence: 13,
    slug: 'despacha-pecas-estoque',
    name: 'Despacha pecas do estoque',
    method: 'POST',
    url: '{{baseUrl}}/parts/service-orders/{{serviceOrderId}}/dispatch',
    auth,
    tests: [
      'test("pecas despachadas no smoke", function () {',
      '  expect(res.getStatus()).to.equal(200);',
      '  expect(res.getBody().dispatched).to.equal(true);',
      '});',
      ...stopOnError,
    ],
  },
  {
    sequence: 14,
    slug: 'finaliza-os',
    name: 'Finaliza OS',
    method: 'PATCH',
    url: '{{baseUrl}}/service-orders/{{serviceOrderId}}/complete',
    auth,
    tests: [
      'test("OS finalizada", function () {',
      '  expect(res.getStatus()).to.equal(200);',
      '  expect(res.getBody().status).to.equal("COMPLETED");',
      '});',
      ...stopOnError,
    ],
  },
  {
    sequence: 15,
    slug: 'gera-cobranca',
    name: 'Gera cobranca',
    method: 'POST',
    url: '{{baseUrl}}/billings',
    auth,
    headers: json,
    body: { serviceOrderId: '{{serviceOrderId}}' },
    tests: [
      'test("cobranca gerada", function () {',
      '  expect(res.getStatus()).to.equal(201);',
      '  expect(res.getBody().amount).to.equal(199.8);',
      '});',
      ...captureId('billingId'),
    ],
  },
  {
    sequence: 16,
    slug: 'entrega-os-opcional',
    name: 'Entrega OS opcional',
    method: 'POST',
    url: '{{baseUrl}}/billings/{{billingId}}/deliver-service-order',
    auth,
    tags: ['optional'],
    tests: [
      'test("entrega depende de pagamento", function () {',
      '  expect(res.getStatus()).to.be.oneOf([204, 409]);',
      '});',
      'if (res.getStatus() === 409) {',
      '  console.log("Pagamento ainda nao confirmado. Confirme webhook Stripe e rode npm run bruno:smoke:optional-delivery.");',
      '}',
    ],
  },
];

export const collection: SmokeCollection = {
  name: 'Oficina FIAP - Smoke QA',
  folder: 'bruno/oficina-fiap-smoke',
  environmentName: 'local',
  steps,
};

